version: '2'
services:
    gateway-mongodb:
        container_name: gateway-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/gateway/mongodb/:/data/db/
